# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
