# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160717_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_post',
            field=models.DateTimeField(),
        ),
    ]
