# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20160717_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='text_body',
            new_name='Text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='time_post',
            new_name='Time',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
