# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 00:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20160717_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Text',
            new_name='text_body',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Time',
            new_name='time_post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Name',
            new_name='title',
        ),
    ]
