# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20160717_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/media/'),
        ),
    ]
