# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20161007_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='author',
        ),
        migrations.AddField(
            model_name='post',
            name='num_of_comments',
            field=models.IntegerField(default=0),
        ),
    ]
